# settings > secret
name: secret test

on: [push]

jobs:
  print-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Password
        env:
          MY_PASSWORD: ${{ secrets.PASSWORD }}
        run: echo $MY_PASSWORD
